[WIP] Add guide on using retworkx for networkx users
Qiskit/retworkx pull request #252
Opened 2021-02-17 22:47 UTC by mtreinish

This commit adds a new documentation guide for current networkx users on
how to start using retworkx or how to migrate existing networkx code. It
provides a high level explanation of the differences in behavior between
the 2 libraries and how you can you can switch between them.

Fixes #248

TODO:

- [ ] Finish writing guide
- [ ] Wait for #118 which adds the multigraph constructor option

2021-02-24 12:43 UTC, mtreinish commented
I think there is still some more we can add here, but this is a decent starting point we can always expand the guide over time. But if people think there are obvious gaps we can add to this before merging.

2021-02-25 16:03 UTC, kdk approved these changes
Looks good on the whole. Few small comments.

2021-02-25 16:03 UTC, kdk commented on docs/source/networkx.rst
> +     - retworkx requires a list of either a 3 or 2 tuple (depend on whether
```suggestion
     - retworkx requires a list of either a 3 or 2 tuple (depending on whether
```

2021-02-25 16:03 UTC, kdk commented on docs/source/networkx.rst
> +networkx is a mature library that has wide user base and extensive feature set,
```suggestion
networkx is a mature library that has a wide user base and extensive feature set,
```

2021-02-25 16:26 UTC, mtreinish commented on docs/source/networkx.rst
> +dictionary) and interact with the graph using the objects you're putting
Yeah, I had a hard time wording it, a networkx graph where a node is an index on a dict for itself. Do you have any thoughts on a clearer wording here? Or is it fine as is in combination with the rest of the paragraph and the code examples?

2021-02-25 18:11 UTC, kdk commented on docs/source/networkx.rst
> +dictionary) and interact with the graph using the objects you're putting
Maybe to move the examples up, something like:

```
The biggest difference to keep in mind is that networkx is very dynamic in how it
can be used, whereas retworkx, being written in rust, puts more constraints on how
you interact with graph object. networkx allows you to treat a graph object
like a python dictionary and interact with the graph using the objects you've inserted,
while with retworkx each node and edge is assigned an integer index
which must be used to access nodes and edges on the graph.

For example...
```

2021-02-25 18:18 UTC, mtreinish commented on docs/source/networkx.rst
> +dictionary) and interact with the graph using the objects you're putting
Ok, I gave that a try in: https://github.com/Qiskit/retworkx/pull/252/commits/93603104fb2ebb575f50459647c336ed949fcb93

2021-02-26 02:00 UTC, elfrocampeador requested changes
Pedantic copy editing, as is tradition

2021-02-26 02:00 UTC, elfrocampeador commented on docs/source/networkx.rst
> +while retworkx by comparison is a much younger library and is missing a lot
```suggestion
while retworkx, by comparison, is a much younger library and is missing a lot
```

2021-02-26 19:15 UTC, merged