Add is_maximal_matching and is_matching functions
Qiskit/retworkx pull request #256
Opened 2021-02-24 22:34 UTC by mtreinish

This commit adds new functions for checking a provided matching set is
valid, is_matching(), and that a provided matching set is valid and
maximal, is_maximal_set(). This pairs with #229 and can be used to
partially check the output from the max_weight_matching function added
there. Equivalent functions were implemented in #229 using Python for
the tests in #229 and those tests should be updated to use these
functions instead.

Fixes #255

2021-03-01 08:12 UTC, itoko requested changes
Thank you for a quick follow-up PR. I think we can simplify the implementation of `_inner_is_matching`.

2021-03-01 13:11 UTC, mtreinish commented on src/lib.rs
> +    let combinations = matching_combinations(matching);
Oh, yeah that's a good idea. I was just looking at the networkx implementation that was using combinations and didn't think it through and just mirrored that here. But yyeah, just checking for duplicate endpoints by iterating over the list in the matching is should be sufficient and much less complicated.

2021-03-01 14:44 UTC, mtreinish commented on src/lib.rs
> +    let combinations = matching_combinations(matching);
Done in: https://github.com/Qiskit/retworkx/pull/256/commits/a81117b4975538dacc26c3ccb0e5397cb8bed374

2021-03-01 14:44 UTC, mtreinish commented on src/lib.rs
> +/// Check if a matching is a maximal matching for a graph
I added this in: https://github.com/Qiskit/retworkx/pull/256/commits/45c882a9d32612f5cd05ee1a7559c3d5784739fb let me know if you think I need to make it more clear.

2021-03-02 00:09 UTC, itoko approved these changes

2021-03-02 00:18 UTC, itoko commented on src/lib.rs
> +/// Check if a matching is a maximal matching for a graph
LGTM. Thanks!

2021-03-02 00:41 UTC, merged